audio_cache = true
use_nerdfont = true
[Keybindings]
[theme]
primary = "light white"
secondary = "light black"
title = "green"
playing = "yellow"
playing_bg = "black"
highlight = "light white"
highlight_bg = "#484848"
error = "light white"
error_bg = "red"
statusbar = "black"
statusbar_progress = "green"
statusbar_bg = "green"
cmdline = "light white"
cmdline_bg = "black"


